import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Modal, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Image } from 'expo-image';
import { useAuth } from "../../context/AuthContext";
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import { bookingService, BOOKING_TIMES, bookingDate, bookingTime, bookingWhen, bookingPreference, bookingPrice, money } from '../../services/bookingService';
import { complaintService } from '../../services/complaintService';
import { paymentService } from '../../services/paymentService';
import { COLORS } from '../../constants/theme';

const ASSETS = {
  accent: require('../../../assets/images/booking/availability-imgBackgroundAccent.svg'),
  avatar: require('../../../assets/images/booking/availability-imgProviderProfileImage.svg'),
  dot: require('../../../assets/images/booking/availability-imgEllipse.svg'),
  selectedDot: require('../../../assets/images/booking/availability-imgEllipse1.svg'),
  selected: require('../../../assets/images/booking/availability-imgEllipse2.svg'),
  arrow: require('../../../assets/images/booking/availability-imgCtaArrow.svg'),
  success: require('../../../assets/images/booking/sent-imgEllipse.svg'),
};
const errorMessage = e => e.response?.data?.message || 'Unable to connect. Please try again.';
const initials = name => (name || '').trim().split(/\s+/).slice(0, 2).map(s => s[0]).join('').toUpperCase();
const localDay = value => new Date(new Date(value).getTime() + 19800000).toISOString().slice(0, 10);
function Button({ title, onPress, disabled, secondary, danger, arrow }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ disabled: !!disabled }} disabled={disabled} onPress={onPress} style={[s.button, secondary && s.secondary, danger && s.danger, disabled && s.disabled]}><Text style={[s.buttonText, arrow && { paddingHorizontal: 24 }, secondary && s.link, danger && s.dangerText]}>{title}</Text>{arrow && <Image source={ASSETS.arrow} style={{ width: 20, height: 20, position: 'absolute', right: 20 }} />}</Pressable>;
}
function Status({ status }) {
  return <View style={[s.status, ['confirmed', 'completed'].includes(status) && s.statusGreen, ['cancelled', 'rejected'].includes(status) && s.danger]}><Text style={[s.statusText, ['confirmed', 'completed'].includes(status) && { color: '#08734C' }, ['cancelled', 'rejected'].includes(status) && s.dangerText]}>{({ pending: 'Requested', time_proposed: 'Review time', awaiting_quote: 'Quote needed', quote_pending: 'Review quote', confirmed: 'Confirmed', inspection_confirmed: 'Inspection booked', inspecting: 'Inspection done', ongoing: 'In progress', completed: 'Completed', rejected: 'Declined', cancelled: 'Cancelled' }[status] || status).replaceAll('_', ' ').toUpperCase()}</Text></View>;
}
function Detail({ label, value, edit }) {
  return <View style={s.detail}><View style={s.flex}><Text style={s.caption}>{label}</Text><Text style={s.value}>{value}</Text></View>{edit && <Pressable accessibilityRole="button" accessibilityLabel={`Edit ${label}`} onPress={edit} style={s.edit}><Text style={s.link}>Edit</Text></Pressable>}</View>;
}

function nextAction(b) {
  if (b.payment?.status === 'paid') return ['Paid', 'The provider confirmed receipt. Your receipt is available.', 'View receipt'];
  if (b.payment?.status === 'awaiting_confirmation') return ['Payment reported', 'The provider needs to confirm receipt. You can report an issue if you need help.', 'Payment details'];
  if (b.invoice && b.payment?.status === 'unpaid' && b.history?.some(h => h.action === 'payment_reject')) return ['Payment receipt not confirmed', 'Check your payment with the provider before paying again. You can report an issue or report the payment again once checked.', 'Review payment'];
  return ({
    pending: ['Waiting for provider response', 'The provider must accept your request. You can message them or cancel while waiting.', 'View request'],
    time_proposed: ['Review a suggested time', 'Your provider suggested another appointment. Accept it or keep your request.', 'Review suggested time'],
    awaiting_quote: ['Appointment accepted — waiting for a quote', 'Your provider will send an itemised quote. No work or charge is agreed yet.', 'View booking'],
    quote_pending: ['Waiting for your approval', 'Review the scope and total. Work is paused until you decide.', 'Review quote'],
    confirmed: ['Appointment confirmed', 'Your provider will attend at the agreed time and update progress.', 'View appointment'],
    inspection_confirmed: ['Inspection booked', 'Your provider will inspect the problem. Repairs need a separate approved quote.', 'View inspection'],
    inspecting: ['Waiting for a repair quote', 'The inspection is recorded. The agreed inspection fee applies if you decline repairs.', 'View booking'],
    ongoing: ['Work in progress', 'Your provider will mark the agreed work complete. Extra work needs your approval.', 'Track work'],
    completed: ['Work completed — invoice available', 'Review the invoice. Pay the provider, then report your payment here.', 'Invoice & payment'],
    cancelled: ['Booking cancelled', 'This request is closed. You can explore providers for a new request.', 'View details'],
    rejected: ['Request declined', 'The provider did not accept this request. Choose another provider or time.', 'View details'],
  })[b.status] || ['Booking updated', 'Open your booking to see the latest details.', 'View details'];
}
function NextAction({ booking }) { const [title, text] = nextAction(booking); return <View accessibilityLiveRegion="polite" style={s.bookingInfo}><Text style={s.value}>{title}</Text><Text style={s.subtitle}>{text}</Text>{!!booking.createdAt && <Text style={s.caption}>Request sent {bookingWhen(booking.createdAt)} · Sri Lanka time</Text>}</View>; }

// The existing booking screen owns the flow; no new navigator or route tree.
export function BookingFlowModal({ provider: initialProvider, onClose, onTrack, rescheduling }) {
  const { user } = useAuth();
  const insets = useSafeAreaInsets();
  const [provider, setProvider] = useState(initialProvider), [mode, setMode] = useState('published'), [windowEnd, setWindowEnd] = useState(null);
  const [alternatives, setAlternatives] = useState(null), [finding, setFinding] = useState(false), [alternativeError, setAlternativeError] = useState('');
  const alternativeRequest = useRef(null);
  const [pricing, setPricing] = useState(rescheduling?.pricing || provider.pricing), [accepted, setAccepted] = useState(false);
  const [step, setStep] = useState(rescheduling ? 1 : 2), [slots, setSlots] = useState([]), [loading, setLoading] = useState(true);
  const [error, setError] = useState(''), [availabilityError, setAvailabilityError] = useState(''), [selected, setSelected] = useState(''), [day, setDay] = useState(localDay(new Date()));
  const [week, setWeek] = useState(0), [busy, setBusy] = useState(false), [sent, setSent] = useState(null);
  const [problem, setProblem] = useState(rescheduling?.problem || ''), [location, setLocation] = useState(rescheduling?.location || [user?.location?.address, user?.location?.city].filter(Boolean).join(', ')), [notes, setNotes] = useState(rescheduling?.notes || '');
  const problemInput = useRef(null), locationInput = useRef(null);
  const [attempted, setAttempted] = useState(false);
  const request = useRef(null), lock = useRef(false), submission = useRef(null), scroll = useRef(null);
  const load = useCallback(() => {
    setLoading(true); setAvailabilityError('');
    request.current?.abort(); const controller = new AbortController(); request.current = controller;
    return bookingService.availability(provider.id, controller.signal, rescheduling?.id).then(result => {
      if (!controller.signal.aborted) { setError(''); if (!rescheduling) { setPricing(result.pricing); setAccepted(false); } setSlots(result.slots); }
    }).catch(e => { if (!controller.signal.aborted) setAvailabilityError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
  }, [provider.id, rescheduling]);
  // Initial network load shares the same loading/retry state as manual refresh.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); return () => request.current?.abort(); }, [load]);
  useEffect(() => () => alternativeRequest.current?.abort(), []);
  function go(next) { setError(''); setStep(next); scroll.current?.scrollTo({ y: 0, animated: false }); }
  const today = localDay(new Date());
  const days = Array.from({ length: 7 }, (_, index) => { const d = new Date(`${today}T00:00:00+05:30`); d.setUTCDate(d.getUTCDate() + week * 7 + index); return { date: localDay(d), stamp: d.toISOString() }; });
  const currentSlots = slots.filter(slot => slot.date === day);
  const available = slots.some(slot => slot.available);
  const preference = { startsAt: selected, scheduleMode: mode, windowEnd, status: 'pending' };
  const selectionLabel = selected ? bookingPreference(preference) : 'Choose a date and time';
  const selectedAvailable = mode !== 'published' || slots.some(slot => slot.startsAt === selected && slot.available);
  const canContinue = !!selected && selectedAvailable && new Date(selected) > new Date() && !busy && !loading && !availabilityError;
  const requestedTimes = BOOKING_TIMES.map(time => ({ startsAt: new Date(`${day}T${time}:00+05:30`).toISOString() })).filter(slot => new Date(slot.startsAt) > new Date() && new Date(slot.startsAt) < new Date(new Date().getTime() + 90 * 86400000));
  const nearby = slots.filter(slot => slot.available && slot.date !== day && Math.abs(new Date(slot.startsAt) - new Date(`${day}T08:00:00+05:30`)) < 7 * 86400000).sort((a, b) => Math.abs(new Date(a.startsAt) - new Date(`${day}T08:00:00+05:30`)) - Math.abs(new Date(b.startsAt) - new Date(`${day}T08:00:00+05:30`))).slice(0, 3);
  function choose(value, nextMode = mode, end = null) { alternativeRequest.current?.abort(); setAlternatives(null); setAlternativeError(''); setFinding(false); setSelected(value); setMode(nextMode); setWindowEnd(end); setError(''); }
  async function findProviders() {
    alternativeRequest.current?.abort(); const controller = new AbortController(); alternativeRequest.current = controller; setFinding(true); setAlternativeError('');
    try { const result = await bookingService.alternatives(provider.id, selected, controller.signal); if (!controller.signal.aborted) setAlternatives(result); }
    catch (e) { if (!controller.signal.aborted) setAlternativeError(errorMessage(e)); }
    finally { if (!controller.signal.aborted) setFinding(false); }
  }
  const back = () => { if (busy) return; if (step === 4 || step === (rescheduling ? 1 : 2)) onClose(); else go(step === 3 ? 1 : 2); };
  const displayStep = rescheduling ? (step === 1 ? 1 : step === 3 ? 2 : 1) : step === 2 ? 1 : step === 1 ? 2 : step;
  const totalSteps = rescheduling ? 2 : 3;
  function review() { setAttempted(true); if (!problem.trim() || !location.trim()) { setError('Complete the required fields below.'); scroll.current?.scrollTo({ y: 0, animated: true }); (!problem.trim() ? problemInput : locationInput).current?.focus(); return; } go(1); }
  async function submit() {
    if (lock.current || !canContinue) return;
    lock.current = true; setBusy(true); setError('');
    try {
      let result;
      if (rescheduling) result = await bookingService.update(rescheduling.id, { action: 'reschedule', bookingVersion: rescheduling.version, startsAt: selected, scheduleMode: mode, windowEnd, problem: problem.trim(), location: location.trim(), notes: notes.trim() });
      else {
        const payload = { pricingVersion: pricing?.version, acceptPricing: !!pricing && accepted, acceptQuoteRequest: !pricing && accepted, providerId: provider.id, startsAt: selected, scheduleMode: mode, windowEnd, problem: problem.trim(), location: location.trim(), notes: notes.trim() };
        const fingerprint = JSON.stringify(payload);
        if (submission.current?.fingerprint !== fingerprint) submission.current = { fingerprint, id: `${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}` };
        result = await bookingService.create({ ...payload, requestId: submission.current.id });
      }
      setSent(result); go(4);
    } catch (e) { if (e.response?.status === 409 && !rescheduling) { setSelected(''); setStep(1); await load(); } setError(rescheduling && e.response?.status === 409 ? 'This booking changed. Go back to My Bookings, review its latest details, then reschedule again. Your agreed scope has not been changed.' : errorMessage(e)); }
    finally { lock.current = false; setBusy(false); }
  }
  const titles = ['', 'Choose date & time', 'Booking details', 'Review booking', 'Request sent'];
  return <Modal visible animationType="slide" presentationStyle="fullScreen" onRequestClose={back}><KeyboardAvoidingView style={[s.screen, { paddingTop: insets.top }]} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
    {step === 1 && <Image source={ASSETS.accent} style={s.accent} />}
    <View style={s.flowHeader}><View style={s.headingRow}>{step !== 4 && <Pressable disabled={busy} onPress={back} accessibilityRole="button" accessibilityLabel="Back" style={s.back}><Text style={s.backText}>‹</Text></Pressable>}<Text accessibilityRole="header" style={s.title}>{titles[step]}</Text></View><Text style={s.subtitle}>{step === 1 ? 'Choose a date that suits you' : step === 2 ? provider.category : step === 3 ? 'Check your details before sending' : `Booking ID: ${sent?.reference || ''}`}</Text>{step < 4 && <><View style={s.progress}><View style={[s.progressActive, { width: `${displayStep / totalSteps * 100}%` }]} /></View><Text style={s.caption}>Step {displayStep} of {totalSteps}{rescheduling ? ' · Reschedule' : ''}</Text></>}</View>
    <ScrollView ref={scroll} keyboardShouldPersistTaps="handled" contentContainerStyle={[s.flowContent, { paddingBottom: Math.max(20, insets.bottom) }]}>
      {!!error && <View style={s.errorBox}><Text accessibilityRole="alert" accessibilityLiveRegion="assertive" style={s.dangerText}>{error}</Text>{step === 1 && <Button secondary title="Try again" onPress={load} />}</View>}
      {!!availabilityError && step < 4 && <View style={s.errorBox}><Text accessibilityRole="alert" style={s.dangerText}>Could not check availability and pricing. Your details are kept. {availabilityError}</Text><Button secondary title="Retry availability and pricing" disabled={loading} onPress={load} /></View>}
      {step === 1 && <>
        <View style={[s.card, s.providerCard]}><View style={s.avatar}><Image source={ASSETS.avatar} style={{ width: 64, height: 64 }} /><Text style={s.avatarLetters}>{initials(provider.name)}</Text></View><View style={s.flex}><Text style={s.providerName}>{provider.name}</Text><Text style={s.subtitle}>{provider.category}</Text><Text style={s.availability}>{loading ? 'Checking appointments…' : availabilityError ? 'Availability not checked' : available ? 'Published appointments available' : 'Preferred-time requests welcome'}</Text></View></View>
        {!loading && !availabilityError && !pricing && !rescheduling && <Text style={s.subtitle}>No pricing published? You can still request a visit. Approve an itemised quote before any charge or work.</Text>}
        <View style={s.sectionHeading}><Text style={s.sectionTitle}>Select a date</Text><Text style={s.caption}>{bookingDate(days[0].stamp, { day: undefined, month: 'long', year: 'numeric' })}</Text></View>
        <View style={s.weekControls}><Pressable accessibilityRole="button" accessibilityLabel="Previous week" style={s.weekButton} disabled={week === 0} onPress={() => { setWeek(week - 1); setDay(localDay(new Date(new Date(today + 'T00:00:00+05:30').getTime() + (week - 1) * 7 * 86400000))); choose(''); }}><Text style={[s.link, week === 0 && s.muted]}>‹ Previous</Text></Pressable><Text style={s.caption}>Sri Lanka time</Text><Pressable accessibilityRole="button" accessibilityLabel="Next week" style={s.weekButton} disabled={week >= 12} onPress={() => { setWeek(week + 1); setDay(localDay(new Date(new Date(today + 'T00:00:00+05:30').getTime() + (week + 1) * 7 * 86400000))); choose(''); }}><Text style={[s.link, week >= 12 && s.muted]}>Next ›</Text></Pressable></View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.dates}>{days.map(d => { const active = d.date === day, hasSlots = slots.some(slot => slot.date === d.date && slot.available); return <Pressable key={d.date} accessibilityRole="button" accessibilityLabel={bookingDate(d.stamp, { weekday: 'long', month: 'long' }) + (hasSlots ? ', published appointments available' : ', no published appointments')} aria-pressed={active} accessibilityState={{ selected: active }} onPress={() => { setDay(d.date); choose(''); }} style={[s.date, active && s.active]}><Text style={[s.dayName, active && s.white]}>{bookingDate(d.stamp, { day: undefined, month: undefined, weekday: 'short' }).toUpperCase()}</Text><Text style={[s.dayNumber, active && s.white]}>{bookingDate(d.stamp, { month: undefined })}</Text>{hasSlots && <Image source={active ? ASSETS.selectedDot : ASSETS.dot} style={{ width: 6, height: 6 }} />}</Pressable>; })}</ScrollView>
        <View style={s.row}>{(mode === 'published' ? [['preferred', 'Request another time'], ['flexible', "I’m flexible"]] : [['published', 'Back to published times'], [mode === 'preferred' ? 'flexible' : 'preferred', mode === 'preferred' ? "I’m flexible" : 'Request another time']]).map(([value, label]) => <Pressable key={value} accessibilityRole="button" onPress={() => choose('', value)} style={s.edit}><Text style={s.link}>{label}</Text></Pressable>)}</View>
        <Text style={s.subtitle}>{mode === 'published' ? 'Choose a published appointment. The provider still needs to accept your request.' : mode === 'preferred' ? 'Choose the time that suits you. This is a request, not verified availability. The provider will confirm or suggest an alternative.' : 'Choose a window you can attend. The provider may confirm a start within it. You must approve any time outside it.'}</Text>
        <Text style={s.sectionTitle}>{mode === 'flexible' ? 'Preferred arrival window' : mode === 'preferred' ? 'Your preferred time' : 'Published appointments'}</Text>
        {mode === 'published' ? loading ? <ActivityIndicator color={COLORS.primary} style={s.loader} /> : availabilityError ? null : !currentSlots.some(slot => slot.available) ? <View style={s.card}><Text style={s.value}>No published appointments available on this date</Text><Text style={s.subtitle}>Keep your date and send a preferred-time request, choose a flexible window, or try a nearby appointment.</Text><Button title="Request my preferred time" onPress={() => choose('', 'preferred')} /><Button secondary title="Choose a flexible window" onPress={() => choose('', 'flexible')} /><Button secondary title="Refresh availability" onPress={load} /></View> : <View style={s.timeGrid}>{currentSlots.map(slot => <Pressable key={slot.startsAt} disabled={!slot.available} accessibilityRole="button" accessibilityLabel={bookingTime(slot.startsAt)} aria-pressed={selected === slot.startsAt} accessibilityState={{ disabled: !slot.available, selected: selected === slot.startsAt }} onPress={() => choose(slot.startsAt)} style={[s.time, !slot.available && s.noSlots, selected === slot.startsAt && s.active]}><Text style={[s.value, !slot.available && s.muted, selected === slot.startsAt && s.white]}>{bookingTime(slot.startsAt)}</Text><Text style={[s.caption, selected === slot.startsAt && s.white]}>{slot.available ? (selected === slot.startsAt ? '✓ Selected' : 'Available to request') : 'Reserved'}</Text></Pressable>)}</View> : mode === 'preferred' ? <View style={s.timeGrid}>{requestedTimes.map(slot => <Pressable accessibilityRole="button" accessibilityLabel={'Request ' + bookingTime(slot.startsAt)} aria-pressed={selected === slot.startsAt} accessibilityState={{ selected: selected === slot.startsAt }} key={slot.startsAt} onPress={() => choose(slot.startsAt)} style={[s.time, selected === slot.startsAt && s.active]}><Text style={[s.value, selected === slot.startsAt && s.white]}>{bookingTime(slot.startsAt)}</Text></Pressable>)}</View> : <View style={s.timeGrid}>{[['Morning', '08:00', '12:00'], ['Afternoon', '12:00', '18:00']].map(([label, from, to]) => { const end = new Date(day + 'T' + to + ':00+05:30').toISOString(), start = requestedTimes.find(slot => slot.startsAt >= new Date(day + 'T' + from + ':00+05:30').toISOString() && slot.startsAt < end)?.startsAt; return <Pressable key={label} accessibilityRole="button" accessibilityLabel={label + ' window'} disabled={!start} aria-pressed={selected === start} accessibilityState={{ disabled: !start, selected: selected === start }} onPress={() => choose(start, 'flexible', end)} style={[s.time, !start && s.noSlots, selected === start && s.active]}><View><Text style={[s.value, selected === start && s.white]}>{label}</Text><Text style={[s.caption, selected === start && s.white]}>{start ? bookingTime(start) + '–' + bookingTime(end) : 'Already passed'}</Text></View></Pressable>; })}</View>}
        {mode !== 'published' && !requestedTimes.length && <Text style={s.subtitle}>No future choices remain on this day. Select another date.</Text>}
        {mode === 'published' && !!selected && !selectedAvailable && <Text accessibilityRole="alert" style={s.dangerText}>Your selected appointment is no longer available. Choose another option or request a preferred time.</Text>}
        {!availabilityError && !loading && !currentSlots.some(slot => slot.available) && !!nearby.length && <View style={s.card}><Text style={s.value}>Nearby published appointments</Text>{nearby.map(slot => <Button key={slot.startsAt} secondary title={bookingWhen(slot.startsAt)} onPress={() => { setDay(slot.date); const offset = Math.floor((new Date(slot.date + 'T00:00:00+05:30') - new Date(today + 'T00:00:00+05:30')) / 86400000); setWeek(Math.floor(offset / 7)); choose(slot.startsAt, 'published'); }} />)}</View>}
        {!rescheduling && mode === 'preferred' && !!selected && <View style={s.card}><Text style={s.value}>Prefer a published appointment at this time?</Text><Button secondary title={finding ? 'Checking providers…' : 'Find other providers at this time'} disabled={finding} onPress={findProviders} />{!!alternativeError && <Text accessibilityRole="alert" style={s.dangerText}>{alternativeError}</Text>}{alternatives?.length === 0 && <Text style={s.subtitle}>No other providers have published this time. You can still send your request or choose another time.</Text>}{alternatives?.map(other => <Button key={other.id} secondary title={other.name + ' · ' + (other.serviceArea || other.category)} onPress={() => { alternativeRequest.current?.abort(); setAlternatives(null); setLoading(true); setProvider(other); setPricing(other.pricing); setAccepted(false); setMode('published'); setSlots([]); }} />)}{!!alternatives?.length && <Text style={s.caption}>Availability is checked again when sending. Review the provider’s service area and pricing.</Text>}</View>}
        <View style={s.selection}><View style={s.flex}><Text style={s.caption}>Your appointment preference</Text><Text style={s.value}>{selectionLabel}</Text></View>{!!selected && <Pressable accessibilityRole="button" accessibilityLabel="Change appointment preference" style={s.edit} onPress={() => choose('')}><Text style={s.link}>Change</Text></Pressable>}</View>
      </>}
      {step === 2 && <>
        <View style={s.card}><Text style={s.value}>{provider.name}</Text><Text style={s.subtitle}>{selected ? selectionLabel : "Describe the job first, then choose a time."}</Text></View>
        {rescheduling && <Text style={s.subtitle}>Rescheduling keeps the agreed work and address. To change either, cancel and create a new request.</Text>}<Text style={s.label}>Problem description *</Text><TextInput ref={problemInput} accessibilityLabel="Problem description, required" placeholder="Describe the work you need help with" editable={!rescheduling} value={problem} onChangeText={value => { setProblem(value); setError(''); }} maxLength={2000} multiline style={[s.input, s.problem]} />
        {attempted && !problem.trim() && <Text accessibilityRole="alert" style={s.dangerText}>Describe the work you need help with.</Text>}<Text style={s.label}>Service location *</Text><TextInput ref={locationInput} accessibilityLabel="Service location, required" placeholder="House number, street and city" editable={!rescheduling} value={location} onChangeText={value => { setLocation(value); setError(''); }} maxLength={500} style={s.input} />
        {attempted && !location.trim() && <Text accessibilityRole="alert" style={s.dangerText}>Enter the house number, street and city.</Text>}<Text style={s.label}>Access notes (optional)</Text><TextInput accessibilityLabel="Access notes" placeholder="Directions, parking or arrival instructions (optional)" value={notes} onChangeText={value => { setNotes(value); setError(''); }} maxLength={1000} multiline style={[s.input, s.notes]} />
        <View style={[s.card, s.spaced]}><Text style={s.caption}>Pricing</Text><Text style={s.price}>{bookingPrice({ pricing })}</Text></View><View style={s.grow} /><Button title="Choose date & time" onPress={review} />
      </>}
      {step === 3 && <>
        <View style={s.card}><Detail label="Provider" value={provider.name} /><Detail label="Service" value={provider.category} /><Detail label="Date & time" value={selectionLabel} edit={() => go(1)} /><Detail label="Location" value={location} edit={rescheduling ? undefined : () => go(2)} /><Detail label="Pricing" value={bookingPrice(rescheduling || { pricing })} /></View>
        <View style={[s.card, s.spaced]}><Detail label="Problem description" value={problem} edit={rescheduling ? undefined : () => go(2)} />{!!notes && <Detail label="Access notes" value={notes} edit={rescheduling ? undefined : () => go(2)} />}</View>
        <View style={[s.card, s.spaced]}><Text style={s.value}>{rescheduling?.quote?.status === 'accepted' ? rescheduling.quote.scope : pricing?.inclusions || 'Request a quote for the work described. No price or fee is agreed yet.'}</Text>{!!pricing?.exclusions && <Text style={s.subtitle}>Not included: {pricing.exclusions}</Text>}<Text style={s.subtitle}>{rescheduling?.quote?.status === 'accepted' ? 'Your previously approved scope and total stay unchanged. Only the appointment time needs confirmation again.' : !pricing ? 'The provider must send an itemised quote for your approval before any work or charge.' : pricing?.type === 'inspection' ? 'This request covers the inspection only. The disclosed inspection fee remains payable if you decline repairs. Repairs require your approval of a separate quote.' : pricing?.type === 'estimate' ? 'This is an estimate. Review and approve an itemised quote before work begins.' : 'The fixed total covers the scope above. Any extra work requires your approval of a revised quote.'}</Text><Text style={s.subtitle}>Nothing to pay now. Pay after completion by cash or bank transfer.</Text>{!rescheduling && <Pressable accessibilityRole="checkbox" aria-checked={accepted} accessibilityState={{ checked: accepted }} {...(Platform.OS === 'web' ? { onKeyDown: e => { if (e.key === ' ' || e.key === 'Enter') { e.preventDefault(); setAccepted(value => !value); } } } : {})} onPress={() => setAccepted(!accepted)} style={s.selection}><Text style={s.link}>{accepted ? '☑' : '☐'} {pricing ? 'I agree to this pricing and scope.' : 'I understand a quote is required; no charge is agreed.'}</Text></Pressable>}</View><View style={s.grow} /><Button disabled={!canContinue || (!rescheduling && !accepted)} title={busy ? 'Sending…' : rescheduling ? 'Send reschedule request' : 'Send booking request'} onPress={submit} />
      </>}
      {step === 4 && sent && <>
        <View style={s.successHero}><View><Image source={ASSETS.success} style={{ width: 88, height: 88 }} /><Text style={s.successCheck}>✓</Text></View><Text style={s.successTitle}>Request sent successfully</Text><Text style={[s.subtitle, s.center]}>{provider.name} will review your request. Track the latest status in My Bookings.</Text></View>
        <View style={s.card}><View style={s.between}><Text style={s.caption}>Current status</Text><Status status={sent.status} /></View><Text style={[s.value, s.spaced]}>Awaiting provider confirmation</Text><Text style={s.subtitle}>Response time depends on the provider. No appointment is confirmed yet.</Text>{!!sent.createdAt && <Text style={s.caption}>Sent {bookingWhen(rescheduling ? sent.updatedAt || sent.createdAt : sent.createdAt)} · Sri Lanka time</Text>}</View>
        <View style={[s.card, s.spaced]}><Text style={s.value}>{bookingPreference(sent)}</Text><Text style={s.subtitle}>{sent.location} • {bookingPrice(sent)}</Text></View><View style={s.grow} /><Button title="Track in My Bookings" onPress={onTrack} /><Button secondary title="Find another provider" onPress={onClose} />
      </>}
    </ScrollView>
    {step === 1 && <View style={[s.flowFooter, { paddingBottom: Math.max(12, insets.bottom) }]}><Button title="Review booking" arrow disabled={!canContinue} onPress={() => go(3)} /><Text style={[s.caption, s.center]}>{canContinue ? 'Provider confirmation is required' : loading ? 'Checking available appointments…' : availabilityError ? 'Retry availability and pricing to continue.' : !selected ? 'Select a time or request another time to continue.' : 'Choose a future, available time to continue.'}</Text></View>}
  </KeyboardAvoidingView></Modal>;
}

export default function BookingsScreen({ navigation }) {
  const insets = useSafeAreaInsets();
  const [bookings, setBookings] = useState([]), [tab, setTab] = useState('Upcoming'), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [detail, setDetail] = useState(null), [cancel, setCancel] = useState(false), [busy, setBusy] = useState(false), [reschedule, setReschedule] = useState(null);
  const cancelLock = useRef(false), mutationLock = useRef(false), cancelVersion = useRef(null);
  const request = useRef(null);
  const load = useCallback(async () => { if (mutationLock.current) return; request.current?.abort(); const controller = new AbortController(); request.current = controller; setError(''); try { const data = await bookingService.list(controller.signal); if (!controller.signal.aborted) { setBookings(data); setDetail(current => current ? data.find(b => b.id === current.id) || current : null); } } catch (e) { if (!controller.signal.aborted) setError(errorMessage(e)); } finally { if (!controller.signal.aborted) setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); const timer = setInterval(load, 30000); return () => { clearInterval(timer); request.current?.abort(); }; }, [load]));
  const filtered = bookings.filter(b => tab === 'Upcoming' ? ['pending', 'time_proposed', 'awaiting_quote', 'confirmed', 'inspection_confirmed', 'quote_pending'].includes(b.status) : tab === 'Ongoing' ? ['ongoing', 'inspecting'].includes(b.status) : ['completed', 'cancelled', 'rejected'].includes(b.status)).sort((a, b) => tab === 'Upcoming' ? new Date(a.startsAt) - new Date(b.startsAt) : new Date(b.startsAt) - new Date(a.startsAt));
  async function cancelBooking() { if (cancelLock.current || mutationLock.current) return; cancelLock.current = true; mutationLock.current = true; request.current?.abort(); setBusy(true); try { const updated = await bookingService.update(detail.id, { action: 'cancel', bookingVersion: cancelVersion.current }); request.current?.abort(); setBookings(rows => rows.map(b => b.id === updated.id ? updated : b)); setDetail(updated); setCancel(false); setError(''); } catch (e) { setError(errorMessage(e)); } finally { cancelLock.current = false; mutationLock.current = false; setBusy(false); } }
  return <View style={[s.screen, { paddingTop: insets.top }]}><View style={s.listHeader}><Text accessibilityRole="header" style={s.title}>My Bookings</Text><Text style={s.subtitle}>Track and manage service requests</Text><View style={s.tabs}>{['Upcoming', 'Ongoing', 'Completed'].map(t => <Pressable key={t} accessibilityRole="tab" aria-selected={tab === t} accessibilityState={{ selected: tab === t }} onPress={() => setTab(t)} style={[s.tab, tab === t && s.active]}><Text style={[s.tabText, tab === t && s.white]}>{t}</Text></Pressable>)}</View></View>
    <ScrollView contentContainerStyle={s.listContent} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => { setLoading(true); void load(); }} />}>
      {!!error && <View style={s.errorBox}><Text accessibilityRole="alert" style={s.dangerText}>{error}</Text><Button title="Try again" secondary onPress={load} /></View>}
      {loading && <ActivityIndicator color={COLORS.primary} />}
      {!loading && !error && !filtered.length && <View style={s.card}><Text style={s.sectionTitle}>No {tab.toLowerCase()} bookings</Text><Text style={s.subtitle}>Your service requests will appear here.</Text><Button title="Explore providers" secondary onPress={() => navigation.navigate('Explore')} /></View>}
      {filtered.map(b => <View key={b.id} style={s.card}><View style={s.between}>{b.status !== 'pending' && <View style={s.listAvatar}><Text style={s.listInitials}>{initials(b.providerName)}</Text></View>}<Text style={[s.providerName, s.flex]}>{b.providerName}</Text><Status status={b.status} /></View><Text style={s.link}>{b.service}</Text><View style={s.bookingInfo}><Text style={s.value}>{bookingPreference(b)}</Text><Text style={s.caption}>{bookingPrice(b)} • {b.reference}</Text></View><NextAction booking={b} /><View style={s.actions}><Button title={nextAction(b)[2]} onPress={() => { setDetail(b); setCancel(false); }} />{['pending', 'time_proposed', 'awaiting_quote', 'confirmed', 'inspection_confirmed'].includes(b.status) && !b.inspectionPerformed && <><Button secondary title="Reschedule" onPress={() => setReschedule(b)} /><Button danger title="Cancel" onPress={() => { cancelVersion.current = b.version; setDetail(b); setCancel(true); }} /></>}</View></View>)}
    </ScrollView>
    {!!detail && <Modal visible animationType="slide" onRequestClose={() => { if (!busy) setDetail(null); }}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={[s.screen, { paddingTop: insets.top }]}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[s.flowContent, { paddingBottom: Math.max(24, insets.bottom) }]}><Text style={s.title}>{cancel ? 'Cancel booking?' : 'Booking details'}</Text>{!!error && <Text accessibilityRole="alert" style={s.dangerText}>{error}</Text>}<View style={s.card}><Status status={detail.status} /><Detail label="Booking ID" value={detail.reference} /><Detail label="Provider" value={detail.providerName} /><Detail label="Service" value={detail.service} /><Detail label="Appointment" value={bookingPreference(detail)} /><Detail label="Location" value={detail.location} /><Detail label="Problem" value={detail.problem} />{!!detail.notes && <Detail label="Access notes" value={detail.notes} />}<Detail label="Pricing" value={bookingPrice(detail)} /></View>{!cancel && <NextAction booking={detail} />}{!cancel && <Button secondary title="Message provider" disabled={busy} onPress={() => { const bookingId = detail.id; setDetail(null); navigation.navigate('Messages', { bookingId, openRequest: Date.now() }); }} />}{!cancel && <BookingCharges booking={detail} onBusyChange={value => { mutationLock.current = value; if (value) request.current?.abort(); setBusy(value); }} onUpdate={updated => { request.current?.abort(); setDetail(updated); setBookings(rows => rows.map(b => b.id === updated.id ? updated : b)); }} />}{cancel && <><Text style={s.subtitle}>This releases the appointment for other customers.</Text><Button danger title={busy ? 'Cancelling…' : 'Confirm cancellation'} disabled={busy} onPress={cancelBooking} /></>}<Button secondary title={cancel ? 'Keep booking' : 'Back to My Bookings'} disabled={busy} onPress={() => { setDetail(null); setCancel(false); }} /></ScrollView></KeyboardAvoidingView></Modal>}
    {!!reschedule && <BookingFlowModal key={reschedule.id} provider={{ id: reschedule.providerId, name: reschedule.providerName, category: reschedule.service, price: reschedule.price, priceUnit: reschedule.priceUnit, pricing: reschedule.pricing }} rescheduling={reschedule} onClose={() => { setReschedule(null); void load(); }} onTrack={() => { setReschedule(null); setTab('Upcoming'); void load(); }} />}
  </View>;
}

// Quote approval and payment remain in the existing booking details view.
export function BookingCharges({ booking: b, onUpdate, provider = false, onBusyChange }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [reference, setReference] = useState(''), [declining, setDeclining] = useState(false);
  const previous = b.previousApprovedQuote;
  const consequence = previous ? 'Keep the previously agreed scope and total of ' + money(previous.totalMinor) + '. Only the proposed changes are declined.' : b.inspectionPerformed ? 'Decline repairs. The completed inspection fee of ' + money(b.pricing?.inspectionFeeMinor) + ' remains payable.' : 'Declining this quote cancels this request. No work or charge will be agreed.';
  const lock = useRef(false);
  async function run(action, payment = false, method) {
    if (lock.current) return; lock.current = true; setBusy(true); onBusyChange?.(true); setError('');
    try { onUpdate(await (payment ? paymentService.update(b.id, { action, method, reference, reportedAt: b.payment?.reportedAt }) : bookingService.update(b.id, { action, bookingVersion: b.version, quoteVersion: b.quote?.version, proposalVersion: b.proposalVersion }))); return true; }
    catch (e) { setError(errorMessage(e)); return false; } finally { lock.current = false; setBusy(false); onBusyChange?.(false); }
  }
  async function refreshBooking() {
    if (lock.current) return; lock.current = true; setBusy(true); onBusyChange?.(true);
    try { const rows = await bookingService.list(); const current = rows.find(row => row.id === b.id); if (!current) throw new Error(); onUpdate(current); setError(''); }
    catch (e) { setError(errorMessage(e)); } finally { lock.current = false; setBusy(false); onBusyChange?.(false); }
  }
  return <View style={[s.card, s.spaced]}>
    {b.status === 'time_proposed' && <><Text style={s.sectionTitle}>Provider suggested another time</Text><Text style={s.value}>{bookingWhen(b.proposedStartsAt)}</Text><Text style={s.subtitle}>{provider ? 'The customer requested' : 'Your requested time is'} {bookingPreference(b)}. This suggestion is not reserved until {provider ? 'the customer accepts' : 'you accept'}. Your agreed pricing stays the same.</Text>{!provider && <><Button title="Accept suggested time" disabled={busy} onPress={() => run('accept_time')} /><Button secondary title="Keep my requested time" disabled={busy} onPress={() => run('decline_time')} /></>}</>}
    <Text style={s.sectionTitle}>Pricing & payment</Text>{b.status === 'awaiting_quote' && <Text style={s.subtitle}>Appointment accepted. Work can start only after the customer approves the provider’s quote.</Text>}<Text style={s.value}>{bookingPrice(b)}</Text>
    {!!b.pricing?.inclusions && <Text style={s.subtitle}>Included: {b.pricing.inclusions}</Text>}{!!b.pricing?.exclusions && <Text style={s.subtitle}>Excluded: {b.pricing.exclusions}</Text>}
    {b.quote && <><Text style={[s.value, s.spaced]}>Quote {b.quote.version} · {b.quote.status}</Text><Text style={s.subtitle}>{b.quote.scope}</Text>{b.quote.items.map((item, i) => <Detail key={i} label={item.description} value={money(item.amountMinor)} />)}<Detail label="Quote total (all charges)" value={money(b.quote.totalMinor)} /></>}
    {b.status === 'quote_pending' && previous && <View style={s.bookingInfo}><Text style={s.value}>Changes to your agreed quote</Text><Detail label="Previously agreed total" value={money(previous.totalMinor)} /><Detail label="Proposed replacement total" value={money(b.quote.totalMinor)} /><Detail label="Difference" value={(b.quote.totalMinor >= previous.totalMinor ? '+' : '−') + money(Math.abs(b.quote.totalMinor - previous.totalMinor))} /><Text style={s.subtitle}>This replaces the total; it is not an additional charge.</Text><Text style={s.value}>Previously agreed scope</Text><Text style={s.subtitle}>{previous.scope}</Text>{previous.items.map((item, i) => <Detail key={i} label={item.description} value={money(item.amountMinor)} />)}<Text style={s.caption}>Compare these with the proposed scope and items above.</Text></View>}
    {!provider && b.status === 'quote_pending' && <><Text style={s.subtitle}>Work is paused until you decide. Declining a revision keeps any previously agreed work and total. After an inspection, its agreed fee is still payable.</Text><Button title="Approve quote & work" disabled={busy} onPress={() => run('approve_quote')} /><Button secondary title="Decline quote" disabled={busy} onPress={() => setDeclining(b.quote.version)} /></>}
    {!provider && declining && b.status === 'quote_pending' && <View style={s.errorBox}><Text style={s.value}>Decline this quote?</Text><Text style={s.subtitle}>{consequence}</Text>{declining !== b.quote.version && <Text accessibilityRole="alert" style={s.dangerText}>The quote changed. Keep reviewing to check the latest quote before deciding.</Text>}<Button danger title="Confirm decline" disabled={busy || declining !== b.quote.version} onPress={async () => { if (await run('decline_quote')) setDeclining(false); }} /><Button secondary title="Keep reviewing" disabled={busy} onPress={() => setDeclining(false)} /></View>}
    {b.invoice && <><Text style={[s.value, s.spaced]}>Invoice {b.invoice.number}</Text>{b.invoice.items.map((item, i) => <Detail key={i} label={item.description} value={money(item.amountMinor)} />)}<Detail label="Invoice total" value={money(b.invoice.totalMinor)} /><Detail label="Balance due" value={money(b.payment?.status === 'paid' ? 0 : b.invoice.totalMinor)} /><Text style={s.value}>Payment: {(b.payment?.status || 'unpaid').replaceAll('_', ' ')}</Text>
      {!provider && b.payment?.status === 'unpaid' && <>{b.history?.some(h => h.action === 'payment_reject') && <Text accessibilityRole="alert" style={s.dangerText}>The provider could not confirm receipt of your reported payment. Check your cash or bank transaction with them before paying again. Report an issue below if you disagree.</Text>}<Text style={s.subtitle}>Pay the provider after completion. Bank transfers are made using your banking app. These buttons report a payment you already made; they do not transfer money.</Text><Button title="I paid the full amount in cash" disabled={busy} onPress={() => run('report', true, 'cash')} />{!!b.invoice.bankDetails && <Text style={s.value}>Bank transfer details: {b.invoice.bankDetails}</Text>}{!b.invoice.bankDetails && <Text style={s.subtitle}>Bank transfer is not available for this invoice. Please use cash.</Text>}<Text style={s.label}>Transfer reference (required for bank transfer)</Text><TextInput editable={!busy && !!b.invoice.bankDetails} accessibilityLabel="Bank transfer reference, required for transfer" placeholder="Bank transfer reference" value={reference} onChangeText={setReference} maxLength={200} style={s.input} /><Button secondary title="I transferred the full amount" disabled={busy || !reference.trim() || !b.invoice.bankDetails} onPress={() => run('report', true, 'bank_transfer')} /></>}
      {b.payment?.status === 'awaiting_confirmation' && <><Text style={s.subtitle}>Payment reported: {money(b.invoice.totalMinor)} · {b.payment.method?.replaceAll('_', ' ')}{b.payment.reference ? ' · Reference: ' + b.payment.reference : ''}{b.payment.reportedAt ? ' · Reported ' + bookingWhen(b.payment.reportedAt) + ' (Sri Lanka time)' : ''}. Waiting for the provider to confirm receipt.</Text>{provider && <><Text style={s.subtitle}>Check your cash or bank account before confirming the full invoice amount.</Text><Button title="Confirm full payment received" disabled={busy} onPress={() => run('confirm', true)} /><Button secondary title="Payment not received" disabled={busy} onPress={() => run('reject', true)} /></>}</>}
      {b.payment?.status === 'paid' && <><Text style={s.value}>Receipt {b.payment.receipt}</Text><Text style={s.subtitle}>{money(b.invoice.totalMinor)} received · {b.payment.method?.replaceAll('_', ' ')} · {bookingDate(b.payment.paidAt)}</Text></>}
    </>}{!provider && <IssueReporter booking={b} disabled={busy} onBusyChange={value => { lock.current = value; setBusy(value); onBusyChange?.(value); }} />}{!!error && <><Text accessibilityRole="alert" accessibilityLiveRegion="assertive" style={s.dangerText}>{error}</Text><Button secondary title="Refresh booking details" disabled={busy} onPress={refreshBooking} /></>}
  </View>;
}

function IssueReporter({ booking, onBusyChange, disabled }) {
  const [refresh, setRefresh] = useState(0), [open, setOpen] = useState(false), [description, setDescription] = useState(''), [cases, setCases] = useState([]), [loading, setLoading] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const lock = useRef(false), input = useRef(null);
  useEffect(() => { if (!open) return; const c = new AbortController(); complaintService.list(booking.id, c.signal).then(rows => { if (!c.signal.aborted) setCases(rows); }).catch(e => { if (!c.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [open, booking.id, refresh]);
  async function send() { if (lock.current || disabled) return; if (!description.trim()) { setError('Describe the issue so support can investigate.'); input.current?.focus(); return; } lock.current = true; setBusy(true); onBusyChange?.(true); setError(''); try { const result = await complaintService.create(booking.id, description.trim()); setCases([result]); } catch (e) { setError(errorMessage(e)); } finally { lock.current = false; setBusy(false); onBusyChange?.(false); } }
  return <View style={s.spaced}><Button secondary title={open ? 'Close issue details' : 'Report an issue / view support case'} disabled={busy || disabled} onPress={() => { setError(''); setLoading(!open); setOpen(!open); }} />{open && <View style={s.bookingInfo}><Text style={s.value}>Booking support</Text><Text style={s.caption}>{booking.reference}</Text>{loading ? <ActivityIndicator color={COLORS.primary} /> : cases.length ? cases.map(c => <View key={c.id}><Text accessibilityLiveRegion="polite" style={s.value}>Case {c.id} · {c.status}</Text><Text style={s.subtitle}>{c.description}</Text><Text style={s.subtitle}>{c.response || 'Your case is in the admin support queue. No response has been recorded yet.'}</Text></View>) : <><Text style={s.subtitle}>Describe the booking or payment problem. This reports an issue to admin support; it does not cancel the booking or change payment.</Text><Text style={s.label}>Issue description *</Text><TextInput ref={input} accessibilityLabel="Issue description, required" multiline maxLength={2000} value={description} onChangeText={value => { setDescription(value); setError(''); }} style={[s.input, s.problem]} /><Button title={busy ? 'Submitting…' : 'Submit issue'} disabled={busy || disabled || !!error} onPress={send} /></>}{!!error && <><Text accessibilityRole="alert" style={s.dangerText}>{error}</Text><Button secondary title="Retry issue support" onPress={() => { setError(''); setLoading(true); setRefresh(v => v + 1); }} /></>}</View>}</View>;
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F6F6F9' },
  accent: { position: 'absolute', width: 160, height: 160, right: -66, top: -65 },
  flowFooter: { paddingHorizontal: 20, paddingTop: 6, gap: 5, backgroundColor: '#F6F6F9', width: '100%', maxWidth: 600, alignSelf: 'center', borderTopWidth: 1, borderColor: '#ECECF1' },
  flowHeader: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 16, width: '100%', maxWidth: 600, alignSelf: 'center' },
  headingRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  back: { width: 44, minHeight: 44, justifyContent: 'center' }, backText: { fontSize: 30, color: '#272727' },
  title: { fontSize: 22, fontWeight: '700', color: '#272727', flexShrink: 1 },
  subtitle: { fontSize: 13, lineHeight: Platform.OS === 'web' ? '1.538em' : 20, color: '#6E6E76', marginTop: 5 },
  progress: { height: 5, borderRadius: 4, backgroundColor: '#ECECF1', marginTop: 14, marginBottom: 8, overflow: 'hidden' },
  progressActive: { height: 5, backgroundColor: COLORS.primary },
  flowContent: { flexGrow: 1, paddingHorizontal: 20, gap: 10, paddingTop: 4, width: '100%', maxWidth: 600, alignSelf: 'center' },
  card: { backgroundColor: '#FFF', padding: 16, borderRadius: 16, boxShadow: '0px 5px 12px rgba(38,38,38,0.06)' },
  providerCard: { flexDirection: 'row', alignItems: 'center', gap: 16, minHeight: 108, borderWidth: 1, borderColor: '#E3E0F2' },
  avatar: { width: 64, height: 64, alignItems: 'center', justifyContent: 'center' }, avatarLetters: { position: 'absolute', color: COLORS.primary, fontSize: 18, fontWeight: '700' },
  providerName: { fontSize: 17, color: '#272727', fontWeight: '700' },
  flex: { flex: 1, minWidth: 0 }, row: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 }, between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  availability: { color: '#08734C', backgroundColor: '#E8F7F0', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 20, fontSize: 10 },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12, gap: 8 }, sectionTitle: { flexShrink: 1, fontSize: 18, fontWeight: '700', color: '#272727' },
  caption: { fontSize: 11, color: '#6E6E76', lineHeight: Platform.OS === 'web' ? '1.545em' : 17 }, link: { color: COLORS.primary, fontSize: 12, lineHeight: Platform.OS === 'web' ? '1.5em' : 18 },
  weekButton: { minWidth: 44, minHeight: 44, justifyContent: 'center' },
  weekControls: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3 },
  dates: { flexDirection: 'row', flexGrow: 1, gap: 5 }, date: { flex: 1, minWidth: 44, minHeight: 68, borderRadius: 14, borderWidth: 1, borderColor: '#E3E0F2', backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 6 },
  dayName: { fontSize: 10, color: '#6E6E76' }, dayNumber: { fontSize: 17, color: '#272727', fontWeight: '700' },
  active: { backgroundColor: COLORS.primary, borderColor: COLORS.primary }, noSlots: { backgroundColor: '#E8E8F0' }, white: { color: '#FFF' }, muted: { color: '#94949E' },
  timeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, time: { flexBasis: '45%', flexGrow: 1, minWidth: 120, minHeight: 46, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 14, borderWidth: 1, borderColor: '#E3E0F2', backgroundColor: '#FFF', flexDirection: 'column', alignItems: 'flex-start', justifyContent: 'center' },
  check: { position: 'absolute', width: 22, textAlign: 'center', color: '#FFF', fontSize: 14, fontWeight: '700' },
  value: { fontSize: 14, color: '#272727', lineHeight: Platform.OS === 'web' ? '1.5em' : 21, fontWeight: '600' }, legend: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8 },
  selection: { backgroundColor: '#F2EEFE', borderRadius: 16, borderWidth: 1, borderColor: '#D6CCFA', padding: 16, flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  button: { backgroundColor: COLORS.primary, minHeight: 52, paddingHorizontal: 12, paddingVertical: 14, borderRadius: 13, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, marginTop: 6 },
  buttonText: { flexShrink: 1, color: '#FFF', fontSize: 14, fontWeight: '600', textAlign: 'center' }, secondary: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#ECECF1' }, disabled: { opacity: 0.45 }, danger: { backgroundColor: '#FDECED' }, dangerText: { color: '#B52636' },
  label: { fontSize: 13, fontWeight: '600', color: '#272727', marginTop: 14 }, input: { minHeight: 56, padding: 16, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#ECECF1', borderRadius: 12, fontSize: 13, color: '#303030' }, problem: { minHeight: 104, textAlignVertical: 'top' }, notes: { minHeight: 72, textAlignVertical: 'top' },
  spaced: { marginTop: 10 }, price: { fontSize: 16, fontWeight: '700', color: '#272727', marginTop: 8 }, grow: { flexGrow: 1, minHeight: 10 }, detail: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#ECECF1', flexDirection: 'row', gap: 10, alignItems: 'center' }, edit: { padding: 10, minHeight: 44, justifyContent: 'center' },
  successHero: { alignItems: 'center', paddingTop: 28, paddingBottom: 28, gap: 20 }, successCheck: { position: 'absolute', width: 88, lineHeight: 88, textAlign: 'center', color: COLORS.primary, fontSize: 40 }, successTitle: { fontSize: 22, fontWeight: '700', color: '#272727', textAlign: 'center', marginTop: 6 }, center: { textAlign: 'center' },
  status: { maxWidth: '45%', flexShrink: 1, backgroundColor: '#FDF4E1', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 18 }, statusText: { fontSize: 10, color: '#8A5B00' }, statusGreen: { backgroundColor: '#E7F6F0' },
  listHeader: { padding: 20, paddingBottom: 10 }, tabs: { flexDirection: 'row', gap: 8, marginTop: 20 }, tab: { flex: 1, minHeight: 44, borderRadius: 20, borderWidth: 1, borderColor: '#ECECF1', backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center' }, tabText: { fontSize: 12, color: '#303030', fontWeight: '600' },
  listAvatar: { width: 54, height: 54, borderRadius: 16, backgroundColor: '#F1EDFE', alignItems: 'center', justifyContent: 'center' }, listInitials: { fontSize: 16, fontWeight: '700', color: COLORS.primary },
  listContent: { padding: 20, gap: 20, width: '100%', maxWidth: 600, alignSelf: 'center' }, bookingInfo: { backgroundColor: '#F6F6F9', padding: 14, borderRadius: 12, marginTop: 18, gap: 5 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }, errorBox: { backgroundColor: '#FDECED', padding: 14, borderRadius: 12, gap: 8 }, loader: { padding: 30 },
});
