const router = require('express').Router();
const { protect } = require('../middleware/authMiddleware');
const { authorizeRoles } = require('../middleware/roleMiddleware');
const { createBookingController } = require('../controllers/bookingController');
const controller = createBookingController(require('../models/Booking'), require('../models/User'));
router.use(protect);
router.get('/pricing', authorizeRoles('provider'), controller.getPricing);
router.patch('/pricing', authorizeRoles('provider'), controller.savePricing);
router.patch('/schedule-settings', authorizeRoles('provider'), controller.saveScheduleSettings);
router.get('/alternatives/:providerId', authorizeRoles('customer'), controller.alternatives);
router.get('/availability/:providerId', authorizeRoles('customer', 'provider'), controller.availability);
router.post('/slots', authorizeRoles('provider'), controller.publishSlot);
router.delete('/slots', authorizeRoles('provider'), controller.removeSlot);
router.delete('/slots/day', authorizeRoles('provider'), controller.removeDay);
router.get('/notifications', authorizeRoles('provider'), controller.notifications);
router.patch('/:id/notifications/:eventId/read', authorizeRoles('provider'), controller.readNotification);
router.get('/', authorizeRoles('customer', 'provider'), controller.list);
router.get('/:id/messages', authorizeRoles('customer', 'provider'), controller.messages);
router.post('/:id/messages', authorizeRoles('customer', 'provider'), controller.sendMessage);
router.post('/', authorizeRoles('customer'), controller.create);
router.patch('/:id', authorizeRoles('customer', 'provider'), controller.update);
module.exports = router;
